// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kughracqfvdrwqwyypla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Z2hyYWNxZnZkcndxd3l5cGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyNDAxNDIsImV4cCI6MjA5NDgxNjE0Mn0.jMkO4cwGoTrXPE1VCtjIOdbeoGmWJGvNhTcVJKfqSA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});